---
- name: docker installation
  hosts: all

  tasks:

  - name: docker
    become: yes
    become_method: sudo
    apt:
      name: docker-engine
      state: latest
      update_cache: yes
      cache_valid_time: 3600

  - name: python-pip
    become: yes
    become_method: sudo
    apt:
      name: python-pip
      state: latest
      install_recommends: no
      update_cache: yes
      cache_valid_time: 3600

  - name: docker-py
    pip:
      name: docker-py
      state: latest
...
