---
- name: docker installation
  hosts: all
  vars:
    repo: experimental
    gpg_fingerprint: 58118E89F3A912897C070ADBF76221572C52609D

  tasks:
  - name: apt-transport-https installation
    become: yes
    become_method: sudo
    apt:
      name: apt-transport-https
      state: latest
      update_cache: yes
      cache_valid_time: 3600

  - name: docker gpg key
    become: yes
    become_method: sudo
    apt_key:
      keyserver: hkp://pool.sks-keyservers.net:80
      id: "{{ gpg_fingerprint }}"
      state: present
    tags: docker

  - name: apt docker.list
    become: yes
    become_method: sudo
    template:
      src: docker.j2
      dest: /etc/apt/sources.list.d/docker.list
      backup: yes
      mode: 0600
      owner: root
      group: root
    tags: docker

  - name: apt update
    become: yes
    become_method: sudo
    apt:
      update_cache: yes

  - name: docker
    become: yes
    become_method: sudo
    apt:
      name: docker-engine
      state: latest
      update_cache: yes
      cache_valid_time: 3600
    tags: docker

  - name: docker running and enabled
    become: yes
    become_method: sudo
    service:
      name: docker
      state: running
      enabled: yes
    tags: docker

  - name: python-pip
    become: yes
    become_method: sudo
    apt:
      name: python-pip
      state: latest
      install_recommends: no

  - name: docker-py
    pip:
      name: docker-py
      state: latest
    tags: docker
...
